-- Dated, subject-specific attendance used by the teacher portal.
create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  teacher_id text not null references public.teachers(id) on delete cascade,
  subject_code text not null references public.subjects(code) on delete restrict,
  student_id text not null references public.students(id) on delete cascade,
  attendance_date date not null,
  present boolean not null,
  marked_at timestamptz not null default now(),
  unique(subject_code, student_id, attendance_date)
);

-- Keep the roster totals used by the admin Students page in sync with the
-- dated records that power the student portal. This also repairs totals when
-- attendance is inserted, changed, or removed outside the teacher UI.
create or replace function public.sync_student_attendance_totals()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_student_id text := coalesce(new.student_id, old.student_id);
begin
  update public.students s
  set total_classes = totals.total_classes,
      attended_classes = totals.attended_classes
  from (
    select count(*)::integer as total_classes,
           count(*) filter (where present)::integer as attended_classes
    from public.attendance_records
    where student_id = v_student_id
  ) totals
  where s.id = v_student_id;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;

drop trigger if exists attendance_records_sync_student_totals on public.attendance_records;
create trigger attendance_records_sync_student_totals
after insert or update or delete on public.attendance_records
for each row execute function public.sync_student_attendance_totals();

update public.students s
set total_classes = totals.total_classes,
    attended_classes = totals.attended_classes
from (
  select s2.id, count(ar.id)::integer as total_classes,
         count(ar.id) filter (where ar.present)::integer as attended_classes
  from public.students s2
  left join public.attendance_records ar on ar.student_id = s2.id
  group by s2.id
) totals
where s.id = totals.id;
create index if not exists attendance_records_subject_date_idx
  on public.attendance_records(subject_code, attendance_date);
alter table public.attendance_records enable row level security;

create or replace function public.get_subject_attendance(p_teacher_id text,p_subject_code text,p_date date)
returns table(student_id text,present boolean)
language sql security definer set search_path=public as $$
  select ar.student_id,ar.present from attendance_records ar
  join teacher_subjects ts on ts.teacher_id=ar.teacher_id and ts.subject_code=ar.subject_code
  where ar.teacher_id=p_teacher_id and ar.subject_code=p_subject_code and ar.attendance_date=p_date;
$$;

create or replace function public.mark_subject_attendance(p_teacher_id text,p_subject_code text,p_student_id text,p_date date,p_present boolean)
returns table(attended_classes integer,total_classes integer,saved_present boolean)
language plpgsql security definer set search_path=public as $$
declare old_present boolean; had_record boolean;
begin
  if extract(dow from p_date)=0 then raise exception 'Attendance cannot be marked on Sunday'; end if;
  if not exists(select 1 from teacher_subjects ts join subjects sub on sub.code=ts.subject_code join students s on s.department=sub.department and s.year=sub.year join teachers t on t.id=ts.teacher_id where ts.teacher_id=p_teacher_id and ts.subject_code=p_subject_code and s.id=p_student_id and s.is_active and t.is_active) then raise exception 'Student is not in this assigned subject class'; end if;
  select true,ar.present into had_record,old_present from attendance_records ar where ar.subject_code=p_subject_code and ar.student_id=p_student_id and ar.attendance_date=p_date;
  insert into attendance_records(teacher_id,subject_code,student_id,attendance_date,present) values(p_teacher_id,p_subject_code,p_student_id,p_date,p_present) on conflict(subject_code,student_id,attendance_date) do update set teacher_id=excluded.teacher_id,present=excluded.present,marked_at=now();
    -- The attendance_records trigger synchronizes the student totals.
  return query select s.attended_classes,s.total_classes,p_present from students s where s.id=p_student_id;
end $$;

revoke all on function public.get_subject_attendance(text,text,date) from public;
revoke all on function public.mark_subject_attendance(text,text,text,date,boolean) from public;
grant execute on function public.get_subject_attendance(text,text,date) to anon,authenticated;
grant execute on function public.mark_subject_attendance(text,text,text,date,boolean) to anon,authenticated;

create or replace function public.get_subject_attendance_dates(p_teacher_id text,p_subject_code text)
returns table(attendance_date date) language sql security definer set search_path=public,extensions as $$
  select distinct ar.attendance_date from attendance_records ar
  join teacher_subjects ts on ts.teacher_id=p_teacher_id and ts.subject_code=ar.subject_code
  where ar.teacher_id=p_teacher_id and ar.subject_code=p_subject_code
  order by ar.attendance_date;
$$;
revoke all on function public.get_subject_attendance_dates(text,text) from public;
grant execute on function public.get_subject_attendance_dates(text,text) to anon,authenticated;

-- Save a complete class register atomically. A saved register is immutable.
create or replace function public.save_subject_attendance(p_teacher_id text,p_subject_code text,p_date date,p_attendance jsonb)
returns table(student_id text,attended_classes integer,total_classes integer)
language plpgsql security definer set search_path=public,extensions as $$
declare expected integer; supplied integer; item jsonb; sid text; is_present boolean;
begin
  if p_date>current_date then raise exception 'Future attendance cannot be marked'; end if;
  if extract(dow from p_date)=0 then raise exception 'Attendance cannot be marked on Sunday'; end if;
  if exists(select 1 from attendance_records where teacher_id=p_teacher_id and subject_code=p_subject_code and attendance_date=p_date)
    then raise exception 'Attendance for this date has already been saved and cannot be changed'; end if;
  if not exists(select 1 from teacher_subjects ts join teachers t on t.id=ts.teacher_id where ts.teacher_id=p_teacher_id and ts.subject_code=p_subject_code and t.is_active)
    then raise exception 'This subject is not assigned to this active teacher'; end if;
  select count(*) into expected from students s join subjects sub on sub.department=s.department and sub.year=s.year where sub.code=p_subject_code and s.is_active;
  select count(distinct value->>'student_id') into supplied from jsonb_array_elements(p_attendance) where value?'student_id' and value?'present' and jsonb_typeof(value->'present')='boolean';
  if expected=0 or supplied<>expected then raise exception 'Mark every student present or absent before saving'; end if;
  for item in select value from jsonb_array_elements(p_attendance) loop
    sid:=item->>'student_id'; is_present:=(item->>'present')::boolean;
    if not exists(select 1 from students s join subjects sub on sub.department=s.department and sub.year=s.year where sub.code=p_subject_code and s.id=sid and s.is_active)
      then raise exception 'Student % is not in this assigned subject class',sid; end if;
    insert into attendance_records(teacher_id,subject_code,student_id,attendance_date,present) values(p_teacher_id,p_subject_code,sid,p_date,is_present);
  end loop;
  return query select s.id,s.attended_classes,s.total_classes from students s
    where s.id in(select value->>'student_id' from jsonb_array_elements(p_attendance));
end $$;
revoke all on function public.save_subject_attendance(text,text,date,jsonb) from public;
grant execute on function public.save_subject_attendance(text,text,date,jsonb) to anon,authenticated;

create or replace function public.student_subject_attendance(p_student_id text)
returns table(subject_code text,subject_name text,total_classes bigint,attended_classes bigint,attendance_percentage integer)
language sql security definer set search_path=public,extensions as $$
  select sub.code,sub.name,count(ar.id),count(ar.id) filter(where ar.present),
    case when count(ar.id)=0 then 0 else round(100.0*count(ar.id) filter(where ar.present)/count(ar.id))::integer end
  from students s join subjects sub on sub.department=s.department and sub.year=s.year
  left join attendance_records ar on ar.subject_code=sub.code and ar.student_id=s.id
  where s.id=p_student_id and s.is_active group by sub.code,sub.name order by sub.code;
$$;
revoke all on function public.student_subject_attendance(text) from public;
grant execute on function public.student_subject_attendance(text) to anon,authenticated;
