import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Pencil, Plus, Trash2, X } from "lucide-react";
import { SUBJECTS, supabase } from "../../lib/data";
import Toast from "../shared/Toast";

const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"], SLOTS=["09:30 - 10:30","10:30 - 11:30","12:00 - 01:00"], BREAK="11:30 - 12:00 (Break)", TIMES=[SLOTS[0],SLOTS[1],BREAK,SLOTS[2]], CK="campus-class-schedule", SK="campus-sports-day-allocations", input="h-11 rounded-xl border border-stone-300 bg-white px-3 dark:border-slate-600 dark:bg-slate-900";
const local=k=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)), merge=(a,b)=>[...a,...b.filter(x=>!a.some(y=>y.id===x.id))], oneSportsDayPerClass=(remote,cached)=>{const days=new Map();[...cached,...remote].forEach(x=>days.set(`${x.department}-${x.year}`,x));return [...days.values()]}, teaches=(t,c)=>t.teacher_subjects?.some(x=>x.subjects?.code===c)||t.subjectCodes?.includes(c);

export default function Schedule({role,session,teachers=[],canManage=false}){
 const [items,setItems]=useState([]),[sports,setSports]=useState([]),[department,setDepartment]=useState("CSE"),[year,setYear]=useState("1"),[fd,setFd]=useState("CSE"),[fy,setFy]=useState("1"),[code,setCode]=useState(SUBJECTS[0].code),[teacherId,setTeacherId]=useState(""),[day,setDay]=useState("Monday"),[slot,setSlot]=useState(SLOTS[0]),[sportsChoice,setSportsChoice]=useState("Monday"),[filter,setFilter]=useState("all"),[teacherScope,setTeacherScope]=useState("all"),[open,setOpen]=useState(false),[sportsOpen,setSportsOpen]=useState(false),[editId,setEditId]=useState(null),[message,setMessage]=useState("");
 const load=async()=>{if(!supabase){setItems(local(CK));setSports(oneSportsDayPerClass([],local(SK)));return}const [c,s]=await Promise.all([supabase.from("class_schedule").select("*").order("day_index").order("slot"),supabase.from("sports_day_allocations").select("*")]);setItems(c.error?local(CK):c.data||[]);setSports(s.error?oneSportsDayPerClass([],local(SK)):oneSportsDayPerClass(s.data||[],[]))};
 useEffect(()=>{load();window.addEventListener("focus",load);return()=>window.removeEventListener("focus",load)},[]);useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(""),3500);return()=>clearTimeout(timer)},[message]);
 const subjects=useMemo(()=>SUBJECTS.filter(x=>x.department===fd&&+x.year===+fy),[fd,fy]);useEffect(()=>{if(!editId)setCode(subjects[0]?.code||"")},[subjects,editId]);const selected=SUBJECTS.find(x=>x.code===code), choices=useMemo(()=>teachers.filter(t=>teaches(t,code)),[teachers,code]);useEffect(()=>{if(!editId)setTeacherId(choices[0]?.id||"")},[choices,editId]);
 const teacherScopes=[...new Map((session?.teacher_subjects||[]).map(x=>{const s=x.subjects;return [`${s?.department}-${s?.year}`,s]})).values()].filter(Boolean), viewedDepartment=canManage?department:role==="teacher"?(teacherScope==="all"?teacherScopes[0]?.department:teacherScope.split("-")[0]):session?.department, viewedYear=+(canManage?year:role==="teacher"?(teacherScope==="all"?teacherScopes[0]?.year:teacherScope.split("-")[1]):session?.year), allocation=sports.find(x=>x.department===viewedDepartment&&+x.year===viewedYear), sportsDay=allocation?.day, shownDays=filter==="all"?DAYS:[filter];
 const shown=items.filter(x=>(role!=="student"||(x.department===session?.department&&+x.year===+session?.year))&&(role!=="teacher"||teacherScopes.some(s=>s.department===x.department&&+s.year===+x.year))&&(teacherScope==="all"||`${x.department}-${x.year}`===teacherScope)&&(!canManage||(x.department===department&&+x.year===+year))&&(filter==="all"||x.day===filter));
 const add=async e=>{e.preventDefault();if(!selected||!teacherId)return setMessage("Choose a subject and its assigned teacher.");if(sports.some(x=>x.department===selected.department&&+x.year===+selected.year&&x.day===day))return setMessage(`${selected.department} Year ${selected.year} has Sports Day on ${day}. Remove it before adding a class.`);const clash=items.find(x=>x.id!==editId&&x.day===day&&x.slot===slot&&(x.teacher_id===teacherId||(x.department===selected.department&&+x.year===+selected.year)));if(clash)return setMessage(clash.teacher_id===teacherId?"This teacher already has a class in that slot.":"This branch and year already has a class in that slot.");const t=teachers.find(x=>x.id===teacherId),draft={subject_code:selected.code,subject_name:selected.name,department:selected.department,year:+selected.year,teacher_id:teacherId,teacher_name:t?.name||teacherId,day,day_index:DAYS.indexOf(day),slot};let saved={...draft,id:editId||crypto.randomUUID()},remote=false;if(supabase){const query=editId?supabase.from("class_schedule").update(draft).eq("id",editId):supabase.from("class_schedule").insert(saved);const {data,error}=await query.select().single();if(error)return setMessage(error.message);saved=data;remote=true}const next=editId?items.map(x=>x.id===editId?saved:x):[...items,saved];setItems(next);if(!remote)save(CK,next);setOpen(false);setEditId(null);setMessage(remote?(editId?"Class updated.":"Class scheduled."):"Class saved on this browser until the database is available.")};
 const removeClass=async id=>{if(supabase){const {error}=await supabase.from("class_schedule").delete().eq("id",id);if(error)return setMessage(error.message)}const n=items.filter(x=>x.id!==id);setItems(n);save(CK,n);setMessage("Class deleted successfully.")};
 const editClass=x=>{setFd(x.department);setFy(String(x.year));setCode(x.subject_code);setTeacherId(x.teacher_id);setDay(x.day);setSlot(x.slot);setEditId(x.id);setOpen(true)};
 const generateTimetable=async()=>{const working=[...items],created=[],missing=[];for(const subject of SUBJECTS){if(working.some(x=>x.subject_code===subject.code))continue;const teacher=teachers.find(x=>teaches(x,subject.code));if(!teacher){missing.push(subject.code);continue}let placed=false;for(const candidateDay of DAYS){if(sports.some(x=>x.department===subject.department&&+x.year===+subject.year&&x.day===candidateDay))continue;for(const candidateSlot of SLOTS){if(working.some(x=>x.day===candidateDay&&x.slot===candidateSlot&&(x.teacher_id===teacher.id||(x.department===subject.department&&+x.year===+subject.year))))continue;const draft={id:crypto.randomUUID(),subject_code:subject.code,subject_name:subject.name,department:subject.department,year:+subject.year,teacher_id:teacher.id,teacher_name:teacher.name||teacher.id,day:candidateDay,day_index:DAYS.indexOf(candidateDay),slot:candidateSlot};working.push(draft);created.push(draft);placed=true;break}if(placed)break}if(!placed)missing.push(subject.code)}if(!created.length)return setMessage(`No classes were added. ${missing.length?`No valid slot or assigned teacher for: ${missing.join(", ")}.`:"All subjects are already scheduled."}`);let saved=created,remote=false;if(supabase){const {data,error}=await supabase.from("class_schedule").insert(created).select();if(error)return setMessage(`No classes were saved: ${error.message}`);saved=data;remote=true}const next=[...items,...saved];setItems(next);if(!remote)save(CK,next);setMessage(`${saved.length} classes scheduled without teacher or class clashes.${missing.length?` Could not schedule: ${missing.join(", ")}.`:""}`)};
 const allocate=async()=>{if(items.some(x=>x.department===department&&+x.year===+year&&x.day===sportsChoice))return setMessage(`Remove the classes on ${sportsChoice} before allocating Sports Day.`);const draft={id:crypto.randomUUID(),department,year:+year,day:sportsChoice};let saved=draft,remote=false;if(supabase){const {data,error}=await supabase.from("sports_day_allocations").upsert({department,year:+year,day:sportsChoice},{onConflict:"department,year"}).select().single();if(!error){saved=data;remote=true}}const n=[...sports.filter(x=>!(x.department===department&&+x.year===+year)),saved];setSports(n);save(SK,n);setMessage(remote?`${sportsChoice} is now Sports Day.`:`${sportsChoice} is highlighted as Sports Day in this browser. Run schema.sql to save it for everyone.`)};
 const removeSports=async()=>{let remote=false;if(supabase){const {error}=await supabase.from("sports_day_allocations").delete().eq("id",allocation.id);remote=!error}const n=sports.filter(x=>x.id!==allocation.id);setSports(n);if(!remote)save(SK,n);setMessage(remote?"Sports Day removed. Classes can now be scheduled on that day.":"Sports Day removed from this browser.")};const own=new Set((session?.teacher_subjects||[]).map(x=>x.subjects?.code));
 return <section className="mx-auto w-full max-w-7xl" data-role={role}>
 {canManage&&<div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>setOpen(true)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-campus px-5 font-bold text-white"><Plus size={18}/> Schedule a class</button>{sportsDay?<button onClick={removeSports} className="h-11 rounded-xl border border-amber-400 bg-amber-50 px-4 font-bold text-amber-800">Remove {sportsDay} Sports Day</button>:<button onClick={()=>setSportsOpen(true)} className="h-11 rounded-xl border border-amber-400 bg-amber-50 px-4 font-bold text-amber-800">Allocate Sports Day</button>}</div>}
 <div className="mt-6 flex flex-wrap gap-3">{canManage&&<><label>Branch <select value={department} onChange={e=>setDepartment(e.target.value)} className={input}><option>CSE</option><option>ECE</option></select></label><label>Year <select value={year} onChange={e=>setYear(e.target.value)} className={input}>{[1,2,3,4].map(x=><option key={x} value={x}>Year {x}</option>)}</select></label></>}{role==="teacher"&&<label>Class / Year <select value={teacherScope} onChange={e=>setTeacherScope(e.target.value)} className={input}><option value="all">All my classes</option>{teacherScopes.map(x=><option key={`${x.department}-${x.year}`} value={`${x.department}-${x.year}`}>{x.department} · Year {x.year}</option>)}</select></label>}<label className="ml-auto">Day <select value={filter} onChange={e=>setFilter(e.target.value)} className={input}><option value="all">All days</option>{DAYS.map(x=><option key={x}>{x}</option>)}</select></label></div><Toast message={message} onClose={()=>setMessage("")} />
 <div className="mt-4 h-[calc(100vh-25rem)] min-h-96 overflow-scroll rounded-2xl border border-slate-200 bg-white"><table className="min-w-[900px] w-full border-collapse"><thead className="sticky top-0 z-10 bg-slate-50"><tr><th className="sticky left-0 z-20 w-36 border-b border-r bg-slate-50 p-4">Time</th>{shownDays.map(d=><th key={d} className={`min-w-52 border-b p-4 ${d===sportsDay?"bg-amber-100 text-amber-900":""}`}>{d}{d===sportsDay&&" — Sports Day"}</th>)}</tr></thead><tbody>{TIMES.map(time=><tr key={time}><th className="sticky left-0 z-10 border-r border-t bg-white p-4 text-sm text-slate-500">{time}</th>{time===BREAK?<td colSpan={shownDays.length} className="border-t bg-amber-50 text-center font-bold text-amber-700">30-minute break</td>:shownDays.map(d=><td key={d} className={`border-l border-t p-2 align-top ${d===sportsDay?"bg-amber-50":""}`}>{shown.filter(x=>x.day===d&&x.slot===time).map(x=>{const mine=role==="teacher"&&(x.teacher_id===session?.id||own.has(x.subject_code));return <div key={x.id} className={`mb-2 rounded-xl border p-3 ${mine?"border-violet-400 bg-violet-100":"bg-slate-50"}`}><div className="flex gap-2"><div className="min-w-0 flex-1"><b className="block text-sm">{x.subject_name}</b><p className="text-xs text-slate-500">{x.department} · Year {x.year}</p><p className="text-xs text-slate-500">{x.teacher_name}</p></div>{canManage&&<div className="flex gap-2"><button onClick={()=>editClass(x)} className="text-violet-600" aria-label="Edit class"><Pencil size={17}/></button><button onClick={()=>removeClass(x.id)} className="text-red-500" aria-label="Delete class"><Trash2 size={17}/></button></div>}</div></div>})}{d===sportsDay&&!shown.some(x=>x.day===d&&x.slot===time)&&<p className="p-2 text-center text-xs font-bold text-amber-700">Sports Day</p>}</td>)}</tr>)}</tbody></table></div>
 {open&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-900/50 p-4"><form onSubmit={add} className="relative w-full max-w-2xl rounded-3xl bg-white p-6"><button type="button" onClick={()=>setOpen(false)} className="absolute right-4 top-4 p-2"><X/></button><h3 className="text-2xl font-bold">Schedule a class</h3><p className="mt-1 text-sm text-slate-500">Remove the Sports Day allocation before scheduling a class on that day.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><select value={fd} onChange={e=>setFd(e.target.value)} className={input}><option>CSE</option><option>ECE</option></select><select value={fy} onChange={e=>setFy(e.target.value)} className={input}>{[1,2,3,4].map(x=><option key={x} value={x}>Year {x}</option>)}</select><select value={code} onChange={e=>setCode(e.target.value)} className={input}>{subjects.map(x=><option key={x.code} value={x.code}>{x.code} — {x.name}</option>)}</select><select value={teacherId} onChange={e=>setTeacherId(e.target.value)} className={input}><option value="">Select assigned teacher</option>{choices.map(x=><option key={x.id} value={x.id}>{x.name} ({x.id})</option>)}</select><select value={day} onChange={e=>setDay(e.target.value)} className={input}>{DAYS.map(x=><option key={x}>{x}</option>)}</select><select value={slot} onChange={e=>setSlot(e.target.value)} className={input}>{SLOTS.map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="h-11 rounded-xl border px-5">Cancel</button><button className="h-11 rounded-xl bg-campus px-5 font-bold text-white">Add class</button></div></form></div>}
 {sportsOpen&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-900/50 p-4"><div className="relative w-full max-w-md rounded-3xl bg-white p-6"><button onClick={()=>setSportsOpen(false)} className="absolute right-4 top-4 p-2"><X/></button><h3 className="text-2xl font-bold">Allocate Sports Day</h3><p className="mt-3 rounded-xl bg-slate-100 px-4 py-3 font-semibold text-slate-700">{department} · Year {year}</p><label className="mt-5 block font-bold">Sports Day<select value={sportsChoice} onChange={e=>setSportsChoice(e.target.value)} className={input+" mt-2 w-full"}>{DAYS.map(x=><option key={x}>{x}</option>)}</select></label><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setSportsOpen(false)} className="h-11 rounded-xl border px-5">Cancel</button><button onClick={async()=>{await allocate();setSportsOpen(false)}} className="h-11 rounded-xl bg-campus px-5 font-bold text-white">Allocate</button></div></div></div>}
 </section>
}
